[project]
name = "python-open-design"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "librosa>=0.11.0",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "tqdm>=4.67.1",
]
